name: Exercise2

on:
    issues:
      types: [opened, edited]
jobs:
    DisplayIssues:
        runs-on: ubuntu-latest
        steps:
            - name: Get Context Data
              run: echo "${{ toJSON(github.event.issue.comments_url) }}"
    
